[build]
command = "bun run build"
publish = "dist"  # or your actual output folder (e.g. 'build', 'out', etc.)
node_bundler = "none"

[[plugins]]
package = "netlify-plugin-bun"

[build.environment]
BUN_VERSION = "1.1.4"  # or whichever version you prefer
